# Generated by Django 5.2.4 on 2025-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=600, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('social_link_one', models.URLField(null=True)),
                ('social_link_two', models.URLField(null=True)),
                ('social_link_three', models.URLField(null=True)),
            ],
        ),
    ]
