# Generated by Django 5.2.4 on 2025-08-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=50, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_log', to='Profile_api.profile')),
            ],
        ),
    ]
